spring.application.name=expense-tracker-devops

spring.data.mongodb.uri=mongodb+srv://vaideheekumari2802_db_user:Expense123@cluster0.ngrdsiu.mongodb.net/expenseDB?appName=Cluster0

server.port=8081

# Expose actuator endpoints for Prometheus monitoring
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator